version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=SBaitman123!
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=SBaitman123!
      - ME_CONFIG_MONGODB_PORT=27018
      - ME_CONFIG_MONGODB_SERVER=sbaitman-mongo
    #volumes:
    #  - mongo-data: /data/db
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=SBaitman123!
    #volumes:
    #  - postgres-data: var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local



